using RainMeadow;

namespace RainMeadowCompat;

/**<summary>
 * Imagine that this State is what gets sent across the internet.
 * More specifically, any fields marked [OnlineField] will be sent.
 * 
 * This class, then, defines 3 things:
 * 1. What data is synced (fields)
 * 2. How this data is set (constructor)
 * 3. How this data is read (UpdateReceived())
 * </summary>
 */
public abstract class ManuallyUpdatedState : OnlineResource.ResourceData.ResourceDataState
{
    //Tracks when the state was last updated
    [OnlineField]
    ulong LastUpdateTime;
    //Tracks whether this state was generated by the host
    [OnlineField]
    bool IsHost = false;

    /**<summary>
     * You should have a constructor like:
     * public RandomizerState(RandomizerData data) : base(data) { }
     * </summary>
     */
    public ManuallyUpdatedState(ManuallyUpdatedData data) {
        LastUpdateTime = data.ResetUpdateTime();
        IsHost = OnlineManager.lobby != null && OnlineManager.lobby.isOwner;
    }

    /**<summary>
     * Do NOT override this function in your own implementation.
     * Instead, use ReceivedUpdate().
     * </summary>
     */
    public override void ReadTo(OnlineResource.ResourceData data, OnlineResource resource)
    {
        //return if the state has not yet been updated to a newer time
        ManuallyUpdatedData data1 = (ManuallyUpdatedData)data;
        if (LastUpdateTime > data1.LastUpdateTime)
        {
            //If I am the host, I should not be receiving others' data
            //So, send my own!
            if (data1.HostControlled && OnlineManager.lobby.isOwner)
            {
                data1.UpdateData();
                return;
            }
            //Do not acknowledge data from clients, whatsoever!
            else if (data1.HostControlled && !IsHost)
                return;

            UpdateReceived(data1, resource);
        }
    }

    /**<summary>
     * Override this function in your implementation.
     * Imagine that this function is called whenever you receive a new packet.
     * Update your mod data here.
     * </summary>
     */
    public abstract void UpdateReceived(ManuallyUpdatedData data, OnlineResource resource);

    /**<summary>
     * You MUST replace this function in your implementation of the State.
     * This will make joining lobbies impossible if kept this way.
     * For example, if I have:
     * public class RandomizerData : ManuallyUpdatedData
     * 
     * This function should be:
     * public override Type GetDataType() => typeof(RandomizerData);
     * </summary>
     */
    //public abstract Type GetDataType();
}
